# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-490, -200, 2881, 1381))
        self.label.setStyleSheet("*{\n"
"  font-family:century gothic;\n"
" font-size:24px;\n"
"}\n"
"QFrame\n"
"{\n"
" background:r#333;\n"
" border-radius:15px;\n"
"}\n"
"#Form{\n"
"   background:url(D:\\python projects\\Python-Blender-Qt\\images);\n"
"}\n"
"QPushButton\n"
"{\n"
" color:white;\n"
" background:#08202c;\n"
" border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
" color:#333;\n"
"  background:#49ebff;\n"
" border-radius:15px;\n"
"}\n"
"QLAbel\n"
"{\n"
" color:white;\n"
"}\n"
"QLineEdit\n"
"{\n"
" background:transparent;\n"
" border:none;\n"
" color:#717072;\n"
" border-bottom: 1px solid #717072;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Pictures/Saved Pictures/15611.jpg"))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 750, 571, 51))
        self.lineEdit.setStyleSheet("QLineEdit\n"
"{\n"
" font-family:century gothic;\n"
" font-size:20px;\n"
" background:white;\n"
" border:none;\n"
" color:black;\n"
" border-bottom: 1px solid #717072;\n"
"\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 80, 571, 661))
        self.textEdit.setStyleSheet("QTextEdit\n"
"{\n"
" background:transparent;\n"
" border:none;\n"
" color:#717072;\n"
" border-bottom: 1px solid #717072;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 750, 91, 51))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
" color:white;\n"
" background:#08202c;\n"
" border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
" color:#333;\n"
"  background:#49ebff;\n"
" border-radius:15px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 571, 71))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
" background:black;\n"
"}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Case Studies/Vaman/app.jpg"))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 10, 71, 41))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
" color:white;\n"
" background:#08202c;\n"
" border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
" color:#333;\n"
"  background:red;\n"
" border-radius:15px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "To Chat Type here...."))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.pushButton_2.setText(_translate("MainWindow", "END"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
